# Generated by Django 3.1.5 on 2021-03-05 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('identifier', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('friendly_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('onsky', 'On sky'), ('lab', 'Lab'), ('simulation', 'Simulation')], max_length=10)),
                ('stage', models.CharField(choices=[('raw', 'Raw'), ('calibrated', 'Calibrated'), ('reduced', 'Reduced')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('finalized', 'Complete')], default='pending', max_length=10)),
                ('source_path', models.CharField(max_length=2048)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets_owned', to=settings.AUTH_USER_MODEL)),
                ('shared', models.ManyToManyField(blank=True, related_name='datasets_shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=32)),
                ('size_bytes', models.PositiveBigIntegerField(editable=False, verbose_name='size (bytes)')),
                ('state', models.CharField(choices=[('new', 'new'), ('syncing', 'syncing'), ('synced', 'synced')], default='new', max_length=10)),
                ('kind', models.CharField(choices=[('science', 'science'), ('calibration', 'calibration'), ('reference', 'reference'), ('product', 'product')], max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.dataset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datum',
            constraint=models.UniqueConstraint(fields=('dataset', 'filename'), name='unique_object_path'),
        ),
    ]
